"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones, configureBoneyard } from 'boneyard-js/react'

import _dashboard from './dashboard.bones.json'
import _log from './log.bones.json'
import _search from './search.bones.json'
import _food_detail from './food-detail.bones.json'

configureBoneyard({"animate":"shimmer"})

registerBones({
  "dashboard": _dashboard,
  "log": _log,
  "search": _search,
  "food-detail": _food_detail,
})
